---
permalink:      none
markdown:       rdiscount
pygments:       true
auto:           true
port:           5000
# maruku:
#   use_tex:      false
#   use_divs:     false
#   png_dir:      images/latex
#   png_url:      /images/latex
